### PR TITLE
Fix Issue with Inconsistent Ribbon Icon Positioning on Load

### LINKED ISSUE #200: Icon doesn't maintain its position in the ribbon
The plugin's icon is currently displayed at the bottom of my sidebar ribbon. When I move the icon within the ribbon and restart Obsidian, it's at the bottom again. Any other icon maintains its position where ever I put it.

I'm using Obsidian 1.4.14 and Periodic Notes 0.0.17.

### PR DESCRIPTION
**Pull request by itsonlyjames**
Fixes https://github.com/liamcain/obsidian-periodic-notes/issues/200

Prior to this code fix, the ribbon item would always be appended to the bottom—irrespective of users altering their position—due to being called within the `onLayoutReady()` func. The below screenshot highlights the `hiddenItems` object being altered upon reloading the application. 

image

Testing is simple, move the position of any periodic note ribbon item (whether on desktop or mobile), and reload the application. Viewing the position having been altered.

Moving both the `configureRibbonIcons()` and `this.configureCommands()` funcs into `onload()` alleviates the alteration of ribbon item position on both desktop and mobile—after having tested both.  Additionally, after some market research, I found no other plugins adding ribbon items in `onLayoutReady()`, rather, within `onload()`; which is where I found this simple fix. 

Furthermore, I also altered the loading of icons—`addIcon()`—to run prior to `onLayoutReady()`, thus removing the flash seen below. `Reload app without saving` was run to visualise the effect. 

Jul-17-2024 18-59-22

After moving the `addIcon()` funcs to run prior to `onLayoutReady()` the issue is no longer apparent and icons load instantaneously. 

Jul-17-2024 18-59-31

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -64,6 +64,12 @@ export default class PeriodicNotesPlugin extends Plugin {
   }
 
   async onload(): Promise<void> {
+    addIcon("calendar-day", calendarDayIcon);
```
Comment (liamcain) [inline src/main.ts:67]: Why did you move these?

Comment (itsonlyjames) [reply src/main.ts:67]: I mentioned moving them to _before_ `onLayoutReady()` but this was an oversight, I'm not entirely sure which process was blocking rendering but having them at the top meant the ribbon icons loaded instantaneously rather than popping in—I assume the async settings load caused the wait. The gifs highlighting this are in the description.  👍
